# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /root/StuntsMultiplayer/desmume-wasm/desmume/wasm-port

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /root/StuntsMultiplayer/desmume-wasm/desmume/wasm-port

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /root/StuntsMultiplayer/desmume-wasm/desmume/wasm-port/CMakeFiles /root/StuntsMultiplayer/desmume-wasm/desmume/wasm-port/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /root/StuntsMultiplayer/desmume-wasm/desmume/wasm-port/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named nds

# Build rule for target.
nds: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 nds
.PHONY : nds

# fast build rule for target.
nds/fast:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/build
.PHONY : nds/fast

# target to build an object file
main.o:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/main.o
.PHONY : main.o

# target to preprocess a source file
main.i:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/main.i
.PHONY : main.i

# target to generate assembly for a file
main.s:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/main.s
.PHONY : main.s

# target to build an object file
root/StuntsMultiplayer/desmume-wasm/desmume/src/Database.o:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/Database.o
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/Database.o

# target to preprocess a source file
root/StuntsMultiplayer/desmume-wasm/desmume/src/Database.i:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/Database.i
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/Database.i

# target to generate assembly for a file
root/StuntsMultiplayer/desmume-wasm/desmume/src/Database.s:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/Database.s
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/Database.s

# target to build an object file
root/StuntsMultiplayer/desmume-wasm/desmume/src/FIFO.o:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/FIFO.o
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/FIFO.o

# target to preprocess a source file
root/StuntsMultiplayer/desmume-wasm/desmume/src/FIFO.i:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/FIFO.i
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/FIFO.i

# target to generate assembly for a file
root/StuntsMultiplayer/desmume-wasm/desmume/src/FIFO.s:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/FIFO.s
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/FIFO.s

# target to build an object file
root/StuntsMultiplayer/desmume-wasm/desmume/src/GPU.o:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/GPU.o
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/GPU.o

# target to preprocess a source file
root/StuntsMultiplayer/desmume-wasm/desmume/src/GPU.i:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/GPU.i
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/GPU.i

# target to generate assembly for a file
root/StuntsMultiplayer/desmume-wasm/desmume/src/GPU.s:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/GPU.s
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/GPU.s

# target to build an object file
root/StuntsMultiplayer/desmume-wasm/desmume/src/MMU.o:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/MMU.o
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/MMU.o

# target to preprocess a source file
root/StuntsMultiplayer/desmume-wasm/desmume/src/MMU.i:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/MMU.i
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/MMU.i

# target to generate assembly for a file
root/StuntsMultiplayer/desmume-wasm/desmume/src/MMU.s:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/MMU.s
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/MMU.s

# target to build an object file
root/StuntsMultiplayer/desmume-wasm/desmume/src/NDSSystem.o:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/NDSSystem.o
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/NDSSystem.o

# target to preprocess a source file
root/StuntsMultiplayer/desmume-wasm/desmume/src/NDSSystem.i:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/NDSSystem.i
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/NDSSystem.i

# target to generate assembly for a file
root/StuntsMultiplayer/desmume-wasm/desmume/src/NDSSystem.s:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/NDSSystem.s
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/NDSSystem.s

# target to build an object file
root/StuntsMultiplayer/desmume-wasm/desmume/src/ROMReader.o:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/ROMReader.o
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/ROMReader.o

# target to preprocess a source file
root/StuntsMultiplayer/desmume-wasm/desmume/src/ROMReader.i:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/ROMReader.i
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/ROMReader.i

# target to generate assembly for a file
root/StuntsMultiplayer/desmume-wasm/desmume/src/ROMReader.s:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/ROMReader.s
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/ROMReader.s

# target to build an object file
root/StuntsMultiplayer/desmume-wasm/desmume/src/SPU.o:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/SPU.o
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/SPU.o

# target to preprocess a source file
root/StuntsMultiplayer/desmume-wasm/desmume/src/SPU.i:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/SPU.i
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/SPU.i

# target to generate assembly for a file
root/StuntsMultiplayer/desmume-wasm/desmume/src/SPU.s:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/SPU.s
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/SPU.s

# target to build an object file
root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot1_none.o:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot1_none.o
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot1_none.o

# target to preprocess a source file
root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot1_none.i:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot1_none.i
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot1_none.i

# target to generate assembly for a file
root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot1_none.s:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot1_none.s
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot1_none.s

# target to build an object file
root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot1_retail_auto.o:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot1_retail_auto.o
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot1_retail_auto.o

# target to preprocess a source file
root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot1_retail_auto.i:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot1_retail_auto.i
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot1_retail_auto.i

# target to generate assembly for a file
root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot1_retail_auto.s:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot1_retail_auto.s
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot1_retail_auto.s

# target to build an object file
root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot1_retail_mcrom.o:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot1_retail_mcrom.o
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot1_retail_mcrom.o

# target to preprocess a source file
root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot1_retail_mcrom.i:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot1_retail_mcrom.i
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot1_retail_mcrom.i

# target to generate assembly for a file
root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot1_retail_mcrom.s:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot1_retail_mcrom.s
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot1_retail_mcrom.s

# target to build an object file
root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot1_retail_nand.o:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot1_retail_nand.o
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot1_retail_nand.o

# target to preprocess a source file
root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot1_retail_nand.i:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot1_retail_nand.i
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot1_retail_nand.i

# target to generate assembly for a file
root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot1_retail_nand.s:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot1_retail_nand.s
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot1_retail_nand.s

# target to build an object file
root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot1comp_mc.o:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot1comp_mc.o
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot1comp_mc.o

# target to preprocess a source file
root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot1comp_mc.i:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot1comp_mc.i
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot1comp_mc.i

# target to generate assembly for a file
root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot1comp_mc.s:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot1comp_mc.s
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot1comp_mc.s

# target to build an object file
root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot1comp_protocol.o:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot1comp_protocol.o
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot1comp_protocol.o

# target to preprocess a source file
root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot1comp_protocol.i:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot1comp_protocol.i
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot1comp_protocol.i

# target to generate assembly for a file
root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot1comp_protocol.s:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot1comp_protocol.s
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot1comp_protocol.s

# target to build an object file
root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot1comp_rom.o:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot1comp_rom.o
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot1comp_rom.o

# target to preprocess a source file
root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot1comp_rom.i:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot1comp_rom.i
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot1comp_rom.i

# target to generate assembly for a file
root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot1comp_rom.s:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot1comp_rom.s
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot1comp_rom.s

# target to build an object file
root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot2_none.o:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot2_none.o
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot2_none.o

# target to preprocess a source file
root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot2_none.i:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot2_none.i
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot2_none.i

# target to generate assembly for a file
root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot2_none.s:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot2_none.s
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot2_none.s

# target to build an object file
root/StuntsMultiplayer/desmume-wasm/desmume/src/arm_instructions.o:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/arm_instructions.o
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/arm_instructions.o

# target to preprocess a source file
root/StuntsMultiplayer/desmume-wasm/desmume/src/arm_instructions.i:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/arm_instructions.i
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/arm_instructions.i

# target to generate assembly for a file
root/StuntsMultiplayer/desmume-wasm/desmume/src/arm_instructions.s:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/arm_instructions.s
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/arm_instructions.s

# target to build an object file
root/StuntsMultiplayer/desmume-wasm/desmume/src/arm_jit.o:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/arm_jit.o
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/arm_jit.o

# target to preprocess a source file
root/StuntsMultiplayer/desmume-wasm/desmume/src/arm_jit.i:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/arm_jit.i
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/arm_jit.i

# target to generate assembly for a file
root/StuntsMultiplayer/desmume-wasm/desmume/src/arm_jit.s:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/arm_jit.s
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/arm_jit.s

# target to build an object file
root/StuntsMultiplayer/desmume-wasm/desmume/src/armcpu.o:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/armcpu.o
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/armcpu.o

# target to preprocess a source file
root/StuntsMultiplayer/desmume-wasm/desmume/src/armcpu.i:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/armcpu.i
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/armcpu.i

# target to generate assembly for a file
root/StuntsMultiplayer/desmume-wasm/desmume/src/armcpu.s:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/armcpu.s
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/armcpu.s

# target to build an object file
root/StuntsMultiplayer/desmume-wasm/desmume/src/bios.o:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/bios.o
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/bios.o

# target to preprocess a source file
root/StuntsMultiplayer/desmume-wasm/desmume/src/bios.i:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/bios.i
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/bios.i

# target to generate assembly for a file
root/StuntsMultiplayer/desmume-wasm/desmume/src/bios.s:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/bios.s
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/bios.s

# target to build an object file
root/StuntsMultiplayer/desmume-wasm/desmume/src/cheatSystem.o:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/cheatSystem.o
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/cheatSystem.o

# target to preprocess a source file
root/StuntsMultiplayer/desmume-wasm/desmume/src/cheatSystem.i:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/cheatSystem.i
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/cheatSystem.i

# target to generate assembly for a file
root/StuntsMultiplayer/desmume-wasm/desmume/src/cheatSystem.s:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/cheatSystem.s
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/cheatSystem.s

# target to build an object file
root/StuntsMultiplayer/desmume-wasm/desmume/src/commandline.o:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/commandline.o
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/commandline.o

# target to preprocess a source file
root/StuntsMultiplayer/desmume-wasm/desmume/src/commandline.i:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/commandline.i
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/commandline.i

# target to generate assembly for a file
root/StuntsMultiplayer/desmume-wasm/desmume/src/commandline.s:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/commandline.s
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/commandline.s

# target to build an object file
root/StuntsMultiplayer/desmume-wasm/desmume/src/common.o:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/common.o
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/common.o

# target to preprocess a source file
root/StuntsMultiplayer/desmume-wasm/desmume/src/common.i:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/common.i
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/common.i

# target to generate assembly for a file
root/StuntsMultiplayer/desmume-wasm/desmume/src/common.s:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/common.s
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/common.s

# target to build an object file
root/StuntsMultiplayer/desmume-wasm/desmume/src/cp15.o:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/cp15.o
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/cp15.o

# target to preprocess a source file
root/StuntsMultiplayer/desmume-wasm/desmume/src/cp15.i:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/cp15.i
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/cp15.i

# target to generate assembly for a file
root/StuntsMultiplayer/desmume-wasm/desmume/src/cp15.s:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/cp15.s
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/cp15.s

# target to build an object file
root/StuntsMultiplayer/desmume-wasm/desmume/src/debug.o:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/debug.o
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/debug.o

# target to preprocess a source file
root/StuntsMultiplayer/desmume-wasm/desmume/src/debug.i:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/debug.i
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/debug.i

# target to generate assembly for a file
root/StuntsMultiplayer/desmume-wasm/desmume/src/debug.s:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/debug.s
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/debug.s

# target to build an object file
root/StuntsMultiplayer/desmume-wasm/desmume/src/driver.o:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/driver.o
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/driver.o

# target to preprocess a source file
root/StuntsMultiplayer/desmume-wasm/desmume/src/driver.i:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/driver.i
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/driver.i

# target to generate assembly for a file
root/StuntsMultiplayer/desmume-wasm/desmume/src/driver.s:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/driver.s
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/driver.s

# target to build an object file
root/StuntsMultiplayer/desmume-wasm/desmume/src/emufile.o:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/emufile.o
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/emufile.o

# target to preprocess a source file
root/StuntsMultiplayer/desmume-wasm/desmume/src/emufile.i:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/emufile.i
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/emufile.i

# target to generate assembly for a file
root/StuntsMultiplayer/desmume-wasm/desmume/src/emufile.s:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/emufile.s
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/emufile.s

# target to build an object file
root/StuntsMultiplayer/desmume-wasm/desmume/src/encrypt.o:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/encrypt.o
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/encrypt.o

# target to preprocess a source file
root/StuntsMultiplayer/desmume-wasm/desmume/src/encrypt.i:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/encrypt.i
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/encrypt.i

# target to generate assembly for a file
root/StuntsMultiplayer/desmume-wasm/desmume/src/encrypt.s:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/encrypt.s
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/encrypt.s

# target to build an object file
root/StuntsMultiplayer/desmume-wasm/desmume/src/filter/deposterize.o:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/filter/deposterize.o
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/filter/deposterize.o

# target to preprocess a source file
root/StuntsMultiplayer/desmume-wasm/desmume/src/filter/deposterize.i:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/filter/deposterize.i
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/filter/deposterize.i

# target to generate assembly for a file
root/StuntsMultiplayer/desmume-wasm/desmume/src/filter/deposterize.s:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/filter/deposterize.s
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/filter/deposterize.s

# target to build an object file
root/StuntsMultiplayer/desmume-wasm/desmume/src/filter/xbrz.o:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/filter/xbrz.o
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/filter/xbrz.o

# target to preprocess a source file
root/StuntsMultiplayer/desmume-wasm/desmume/src/filter/xbrz.i:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/filter/xbrz.i
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/filter/xbrz.i

# target to generate assembly for a file
root/StuntsMultiplayer/desmume-wasm/desmume/src/filter/xbrz.s:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/filter/xbrz.s
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/filter/xbrz.s

# target to build an object file
root/StuntsMultiplayer/desmume-wasm/desmume/src/firmware.o:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/firmware.o
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/firmware.o

# target to preprocess a source file
root/StuntsMultiplayer/desmume-wasm/desmume/src/firmware.i:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/firmware.i
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/firmware.i

# target to generate assembly for a file
root/StuntsMultiplayer/desmume-wasm/desmume/src/firmware.s:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/firmware.s
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/firmware.s

# target to build an object file
root/StuntsMultiplayer/desmume-wasm/desmume/src/gfx3d.o:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/gfx3d.o
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/gfx3d.o

# target to preprocess a source file
root/StuntsMultiplayer/desmume-wasm/desmume/src/gfx3d.i:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/gfx3d.i
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/gfx3d.i

# target to generate assembly for a file
root/StuntsMultiplayer/desmume-wasm/desmume/src/gfx3d.s:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/gfx3d.s
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/gfx3d.s

# target to build an object file
root/StuntsMultiplayer/desmume-wasm/desmume/src/libretro-common/encodings/encoding_utf.o:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/libretro-common/encodings/encoding_utf.o
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/libretro-common/encodings/encoding_utf.o

# target to preprocess a source file
root/StuntsMultiplayer/desmume-wasm/desmume/src/libretro-common/encodings/encoding_utf.i:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/libretro-common/encodings/encoding_utf.i
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/libretro-common/encodings/encoding_utf.i

# target to generate assembly for a file
root/StuntsMultiplayer/desmume-wasm/desmume/src/libretro-common/encodings/encoding_utf.s:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/libretro-common/encodings/encoding_utf.s
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/libretro-common/encodings/encoding_utf.s

# target to build an object file
root/StuntsMultiplayer/desmume-wasm/desmume/src/matrix.o:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/matrix.o
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/matrix.o

# target to preprocess a source file
root/StuntsMultiplayer/desmume-wasm/desmume/src/matrix.i:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/matrix.i
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/matrix.i

# target to generate assembly for a file
root/StuntsMultiplayer/desmume-wasm/desmume/src/matrix.s:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/matrix.s
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/matrix.s

# target to build an object file
root/StuntsMultiplayer/desmume-wasm/desmume/src/mc.o:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/mc.o
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/mc.o

# target to preprocess a source file
root/StuntsMultiplayer/desmume-wasm/desmume/src/mc.i:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/mc.i
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/mc.i

# target to generate assembly for a file
root/StuntsMultiplayer/desmume-wasm/desmume/src/mc.s:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/mc.s
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/mc.s

# target to build an object file
root/StuntsMultiplayer/desmume-wasm/desmume/src/metaspu/metaspu.o:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/metaspu/metaspu.o
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/metaspu/metaspu.o

# target to preprocess a source file
root/StuntsMultiplayer/desmume-wasm/desmume/src/metaspu/metaspu.i:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/metaspu/metaspu.i
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/metaspu/metaspu.i

# target to generate assembly for a file
root/StuntsMultiplayer/desmume-wasm/desmume/src/metaspu/metaspu.s:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/metaspu/metaspu.s
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/metaspu/metaspu.s

# target to build an object file
root/StuntsMultiplayer/desmume-wasm/desmume/src/mic.o:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/mic.o
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/mic.o

# target to preprocess a source file
root/StuntsMultiplayer/desmume-wasm/desmume/src/mic.i:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/mic.i
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/mic.i

# target to generate assembly for a file
root/StuntsMultiplayer/desmume-wasm/desmume/src/mic.s:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/mic.s
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/mic.s

# target to build an object file
root/StuntsMultiplayer/desmume-wasm/desmume/src/movie.o:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/movie.o
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/movie.o

# target to preprocess a source file
root/StuntsMultiplayer/desmume-wasm/desmume/src/movie.i:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/movie.i
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/movie.i

# target to generate assembly for a file
root/StuntsMultiplayer/desmume-wasm/desmume/src/movie.s:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/movie.s
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/movie.s

# target to build an object file
root/StuntsMultiplayer/desmume-wasm/desmume/src/path.o:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/path.o
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/path.o

# target to preprocess a source file
root/StuntsMultiplayer/desmume-wasm/desmume/src/path.i:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/path.i
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/path.i

# target to generate assembly for a file
root/StuntsMultiplayer/desmume-wasm/desmume/src/path.s:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/path.s
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/path.s

# target to build an object file
root/StuntsMultiplayer/desmume-wasm/desmume/src/rasterize.o:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/rasterize.o
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/rasterize.o

# target to preprocess a source file
root/StuntsMultiplayer/desmume-wasm/desmume/src/rasterize.i:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/rasterize.i
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/rasterize.i

# target to generate assembly for a file
root/StuntsMultiplayer/desmume-wasm/desmume/src/rasterize.s:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/rasterize.s
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/rasterize.s

# target to build an object file
root/StuntsMultiplayer/desmume-wasm/desmume/src/readwrite.o:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/readwrite.o
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/readwrite.o

# target to preprocess a source file
root/StuntsMultiplayer/desmume-wasm/desmume/src/readwrite.i:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/readwrite.i
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/readwrite.i

# target to generate assembly for a file
root/StuntsMultiplayer/desmume-wasm/desmume/src/readwrite.s:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/readwrite.s
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/readwrite.s

# target to build an object file
root/StuntsMultiplayer/desmume-wasm/desmume/src/render3D.o:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/render3D.o
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/render3D.o

# target to preprocess a source file
root/StuntsMultiplayer/desmume-wasm/desmume/src/render3D.i:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/render3D.i
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/render3D.i

# target to generate assembly for a file
root/StuntsMultiplayer/desmume-wasm/desmume/src/render3D.s:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/render3D.s
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/render3D.s

# target to build an object file
root/StuntsMultiplayer/desmume-wasm/desmume/src/rtc.o:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/rtc.o
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/rtc.o

# target to preprocess a source file
root/StuntsMultiplayer/desmume-wasm/desmume/src/rtc.i:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/rtc.i
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/rtc.i

# target to generate assembly for a file
root/StuntsMultiplayer/desmume-wasm/desmume/src/rtc.s:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/rtc.s
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/rtc.s

# target to build an object file
root/StuntsMultiplayer/desmume-wasm/desmume/src/saves.o:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/saves.o
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/saves.o

# target to preprocess a source file
root/StuntsMultiplayer/desmume-wasm/desmume/src/saves.i:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/saves.i
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/saves.i

# target to generate assembly for a file
root/StuntsMultiplayer/desmume-wasm/desmume/src/saves.s:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/saves.s
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/saves.s

# target to build an object file
root/StuntsMultiplayer/desmume-wasm/desmume/src/slot1.o:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/slot1.o
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/slot1.o

# target to preprocess a source file
root/StuntsMultiplayer/desmume-wasm/desmume/src/slot1.i:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/slot1.i
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/slot1.i

# target to generate assembly for a file
root/StuntsMultiplayer/desmume-wasm/desmume/src/slot1.s:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/slot1.s
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/slot1.s

# target to build an object file
root/StuntsMultiplayer/desmume-wasm/desmume/src/slot2.o:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/slot2.o
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/slot2.o

# target to preprocess a source file
root/StuntsMultiplayer/desmume-wasm/desmume/src/slot2.i:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/slot2.i
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/slot2.i

# target to generate assembly for a file
root/StuntsMultiplayer/desmume-wasm/desmume/src/slot2.s:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/slot2.s
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/slot2.s

# target to build an object file
root/StuntsMultiplayer/desmume-wasm/desmume/src/texcache.o:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/texcache.o
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/texcache.o

# target to preprocess a source file
root/StuntsMultiplayer/desmume-wasm/desmume/src/texcache.i:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/texcache.i
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/texcache.i

# target to generate assembly for a file
root/StuntsMultiplayer/desmume-wasm/desmume/src/texcache.s:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/texcache.s
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/texcache.s

# target to build an object file
root/StuntsMultiplayer/desmume-wasm/desmume/src/thumb_instructions.o:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/thumb_instructions.o
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/thumb_instructions.o

# target to preprocess a source file
root/StuntsMultiplayer/desmume-wasm/desmume/src/thumb_instructions.i:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/thumb_instructions.i
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/thumb_instructions.i

# target to generate assembly for a file
root/StuntsMultiplayer/desmume-wasm/desmume/src/thumb_instructions.s:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/thumb_instructions.s
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/thumb_instructions.s

# target to build an object file
root/StuntsMultiplayer/desmume-wasm/desmume/src/utils/colorspacehandler/colorspacehandler.o:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/utils/colorspacehandler/colorspacehandler.o
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/utils/colorspacehandler/colorspacehandler.o

# target to preprocess a source file
root/StuntsMultiplayer/desmume-wasm/desmume/src/utils/colorspacehandler/colorspacehandler.i:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/utils/colorspacehandler/colorspacehandler.i
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/utils/colorspacehandler/colorspacehandler.i

# target to generate assembly for a file
root/StuntsMultiplayer/desmume-wasm/desmume/src/utils/colorspacehandler/colorspacehandler.s:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/utils/colorspacehandler/colorspacehandler.s
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/utils/colorspacehandler/colorspacehandler.s

# target to build an object file
root/StuntsMultiplayer/desmume-wasm/desmume/src/utils/datetime.o:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/utils/datetime.o
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/utils/datetime.o

# target to preprocess a source file
root/StuntsMultiplayer/desmume-wasm/desmume/src/utils/datetime.i:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/utils/datetime.i
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/utils/datetime.i

# target to generate assembly for a file
root/StuntsMultiplayer/desmume-wasm/desmume/src/utils/datetime.s:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/utils/datetime.s
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/utils/datetime.s

# target to build an object file
root/StuntsMultiplayer/desmume-wasm/desmume/src/utils/decrypt/decrypt.o:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/utils/decrypt/decrypt.o
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/utils/decrypt/decrypt.o

# target to preprocess a source file
root/StuntsMultiplayer/desmume-wasm/desmume/src/utils/decrypt/decrypt.i:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/utils/decrypt/decrypt.i
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/utils/decrypt/decrypt.i

# target to generate assembly for a file
root/StuntsMultiplayer/desmume-wasm/desmume/src/utils/decrypt/decrypt.s:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/utils/decrypt/decrypt.s
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/utils/decrypt/decrypt.s

# target to build an object file
root/StuntsMultiplayer/desmume-wasm/desmume/src/utils/decrypt/header.o:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/utils/decrypt/header.o
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/utils/decrypt/header.o

# target to preprocess a source file
root/StuntsMultiplayer/desmume-wasm/desmume/src/utils/decrypt/header.i:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/utils/decrypt/header.i
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/utils/decrypt/header.i

# target to generate assembly for a file
root/StuntsMultiplayer/desmume-wasm/desmume/src/utils/decrypt/header.s:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/utils/decrypt/header.s
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/utils/decrypt/header.s

# target to build an object file
root/StuntsMultiplayer/desmume-wasm/desmume/src/utils/guid.o:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/utils/guid.o
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/utils/guid.o

# target to preprocess a source file
root/StuntsMultiplayer/desmume-wasm/desmume/src/utils/guid.i:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/utils/guid.i
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/utils/guid.i

# target to generate assembly for a file
root/StuntsMultiplayer/desmume-wasm/desmume/src/utils/guid.s:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/utils/guid.s
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/utils/guid.s

# target to build an object file
root/StuntsMultiplayer/desmume-wasm/desmume/src/utils/xstring.o:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/utils/xstring.o
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/utils/xstring.o

# target to preprocess a source file
root/StuntsMultiplayer/desmume-wasm/desmume/src/utils/xstring.i:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/utils/xstring.i
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/utils/xstring.i

# target to generate assembly for a file
root/StuntsMultiplayer/desmume-wasm/desmume/src/utils/xstring.s:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/utils/xstring.s
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/utils/xstring.s

# target to build an object file
root/StuntsMultiplayer/desmume-wasm/desmume/src/version.o:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/version.o
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/version.o

# target to preprocess a source file
root/StuntsMultiplayer/desmume-wasm/desmume/src/version.i:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/version.i
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/version.i

# target to generate assembly for a file
root/StuntsMultiplayer/desmume-wasm/desmume/src/version.s:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/version.s
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/version.s

# target to build an object file
root/StuntsMultiplayer/desmume-wasm/desmume/src/wifi.o:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/wifi.o
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/wifi.o

# target to preprocess a source file
root/StuntsMultiplayer/desmume-wasm/desmume/src/wifi.i:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/wifi.i
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/wifi.i

# target to generate assembly for a file
root/StuntsMultiplayer/desmume-wasm/desmume/src/wifi.s:
	$(MAKE) -f CMakeFiles/nds.dir/build.make CMakeFiles/nds.dir/root/StuntsMultiplayer/desmume-wasm/desmume/src/wifi.s
.PHONY : root/StuntsMultiplayer/desmume-wasm/desmume/src/wifi.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... nds"
	@echo "... edit_cache"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/Database.o"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/Database.i"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/Database.s"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/FIFO.o"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/FIFO.i"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/FIFO.s"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/GPU.o"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/GPU.i"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/GPU.s"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/MMU.o"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/MMU.i"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/MMU.s"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/NDSSystem.o"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/NDSSystem.i"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/NDSSystem.s"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/ROMReader.o"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/ROMReader.i"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/ROMReader.s"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/SPU.o"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/SPU.i"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/SPU.s"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot1_none.o"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot1_none.i"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot1_none.s"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot1_retail_auto.o"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot1_retail_auto.i"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot1_retail_auto.s"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot1_retail_mcrom.o"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot1_retail_mcrom.i"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot1_retail_mcrom.s"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot1_retail_nand.o"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot1_retail_nand.i"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot1_retail_nand.s"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot1comp_mc.o"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot1comp_mc.i"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot1comp_mc.s"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot1comp_protocol.o"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot1comp_protocol.i"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot1comp_protocol.s"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot1comp_rom.o"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot1comp_rom.i"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot1comp_rom.s"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot2_none.o"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot2_none.i"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/addons/slot2_none.s"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/arm_instructions.o"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/arm_instructions.i"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/arm_instructions.s"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/arm_jit.o"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/arm_jit.i"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/arm_jit.s"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/armcpu.o"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/armcpu.i"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/armcpu.s"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/bios.o"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/bios.i"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/bios.s"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/cheatSystem.o"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/cheatSystem.i"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/cheatSystem.s"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/commandline.o"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/commandline.i"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/commandline.s"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/common.o"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/common.i"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/common.s"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/cp15.o"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/cp15.i"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/cp15.s"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/debug.o"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/debug.i"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/debug.s"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/driver.o"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/driver.i"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/driver.s"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/emufile.o"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/emufile.i"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/emufile.s"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/encrypt.o"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/encrypt.i"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/encrypt.s"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/filter/deposterize.o"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/filter/deposterize.i"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/filter/deposterize.s"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/filter/xbrz.o"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/filter/xbrz.i"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/filter/xbrz.s"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/firmware.o"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/firmware.i"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/firmware.s"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/gfx3d.o"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/gfx3d.i"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/gfx3d.s"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/libretro-common/encodings/encoding_utf.o"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/libretro-common/encodings/encoding_utf.i"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/libretro-common/encodings/encoding_utf.s"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/matrix.o"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/matrix.i"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/matrix.s"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/mc.o"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/mc.i"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/mc.s"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/metaspu/metaspu.o"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/metaspu/metaspu.i"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/metaspu/metaspu.s"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/mic.o"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/mic.i"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/mic.s"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/movie.o"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/movie.i"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/movie.s"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/path.o"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/path.i"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/path.s"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/rasterize.o"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/rasterize.i"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/rasterize.s"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/readwrite.o"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/readwrite.i"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/readwrite.s"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/render3D.o"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/render3D.i"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/render3D.s"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/rtc.o"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/rtc.i"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/rtc.s"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/saves.o"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/saves.i"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/saves.s"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/slot1.o"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/slot1.i"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/slot1.s"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/slot2.o"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/slot2.i"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/slot2.s"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/texcache.o"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/texcache.i"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/texcache.s"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/thumb_instructions.o"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/thumb_instructions.i"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/thumb_instructions.s"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/utils/colorspacehandler/colorspacehandler.o"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/utils/colorspacehandler/colorspacehandler.i"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/utils/colorspacehandler/colorspacehandler.s"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/utils/datetime.o"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/utils/datetime.i"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/utils/datetime.s"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/utils/decrypt/decrypt.o"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/utils/decrypt/decrypt.i"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/utils/decrypt/decrypt.s"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/utils/decrypt/header.o"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/utils/decrypt/header.i"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/utils/decrypt/header.s"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/utils/guid.o"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/utils/guid.i"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/utils/guid.s"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/utils/xstring.o"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/utils/xstring.i"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/utils/xstring.s"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/version.o"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/version.i"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/version.s"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/wifi.o"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/wifi.i"
	@echo "... root/StuntsMultiplayer/desmume-wasm/desmume/src/wifi.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

